# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnipboxCli < Formula
  desc "A CLI for Snipbox"
  homepage "https://github.com/Aadithya-J/snipbox-cli"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.2/snipbox-cli_1.0.2_darwin_amd64.tar.gz"
      sha256 "659a66fea8161944ab4e3ab5840f213dc4b153f09ef673cac9f02cb2f14a4416"

      def install
        bin.install "snipbox-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.2/snipbox-cli_1.0.2_darwin_arm64.tar.gz"
      sha256 "a80df26398e4f5c9d1ef497686aa5975edb0baaa613ed64c784431f9eacf4794"

      def install
        bin.install "snipbox-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.2/snipbox-cli_1.0.2_linux_amd64.tar.gz"
      sha256 "279f559de4974813059cf0307ebdf624aa31e193ca3749760264281c8e33b4ca"
      def install
        bin.install "snipbox-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.2/snipbox-cli_1.0.2_linux_arm64.tar.gz"
      sha256 "f1bd0bec0a636e05d031fd77226ac0fe5b1dbd0cfce5a6f5998040c5d73a1d01"
      def install
        bin.install "snipbox-cli"
      end
    end
  end
end
