# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnipboxCli < Formula
  desc "A CLI for Snipbox"
  homepage "https://github.com/Aadithya-J/snipbox-cli"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.5/snipbox-cli_1.0.5_darwin_amd64.tar.gz"
      sha256 "2f77bfc3d87e1cf28758b7176a3d3890ad719e7cc5ec6c22c95831f627eab2e8"

      def install
        bin.install "snipbox-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.5/snipbox-cli_1.0.5_darwin_arm64.tar.gz"
      sha256 "325aa6c7c2c1f3d5238a10d8c8a81c5a68655aac18dd048630f0ae6ccbe4cf46"

      def install
        bin.install "snipbox-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.5/snipbox-cli_1.0.5_linux_amd64.tar.gz"
      sha256 "37ea30e351707d3ca0b5ec6f8dda4c07cbebe03c1e09bdcb5564db5bf7817a30"
      def install
        bin.install "snipbox-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.0.5/snipbox-cli_1.0.5_linux_arm64.tar.gz"
      sha256 "6413d7cb479a8d68e9a491b7a3226dbc163f828378f68dcb0b774fe97ac3771b"
      def install
        bin.install "snipbox-cli"
      end
    end
  end
end
