# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnipboxCli < Formula
  desc "A CLI for Snipbox"
  homepage "https://github.com/Aadithya-J/snipbox-cli"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.1.0/snipbox_1.1.0_darwin_amd64.tar.gz"
      sha256 "d3776ca0cbda8568a8308731f3ef2170b2e825b4683721224881d36845687fa1"

      def install
        bin.install "snipbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.1.0/snipbox_1.1.0_darwin_arm64.tar.gz"
      sha256 "3c68efc75aacde79a630af3711526b8e1f8a499f5317bc7c999b0e1e2ee0cc88"

      def install
        bin.install "snipbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.1.0/snipbox_1.1.0_linux_amd64.tar.gz"
      sha256 "8ec22098a925339a94d931747fedf3f7f5a8cd34a64d2e2982ed67b725f188d0"
      def install
        bin.install "snipbox"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Aadithya-J/snipbox-cli/releases/download/v1.1.0/snipbox_1.1.0_linux_arm64.tar.gz"
      sha256 "bf55130a802ab864cf4d4ebe54b9a2c2ba5b2088320f153524acc72641e01de8"
      def install
        bin.install "snipbox"
      end
    end
  end
end
